- name: Download and install Plex debian package
  become: true
  shell: 'wget -O /tmp/plex.deb https://downloads.plex.tv/plex-media-server-new/1.32.8.7639-fb6452ebf/debian/plexmediaserver_1.32.8.7639-fb6452ebf_amd64.deb && dpkg -i /tmp/plex.deb'
  args:
    creates: /lib/systemd/system/plexmediaserver.service

- name: Add plex user to media group
  become: true
  user:
    name: plex
    groups: media
    append: true

- name: Configure UFW for Plex
  become: true
  notify: reload plex ufw
  template:
    dest: /etc/ufw/applications.d/plexmediaserver
    src: templates/plex-ufw.conf

- name: Allow plex via UFW
  become: true
  ufw:
    app: plexmediaserver-all
    rule: allow
